/**
 * Strategic maritime chokepoints and canals. Positions mark the narrowest
 * navigable section; figures are rounded public estimates for context only.
 */
export const MARITIME_CHOKEPOINTS = Object.freeze([
  {
    id: 'hormuz',
    name: 'Strait of Hormuz',
    kind: 'strait',
    coords: [56.45, 26.57],
    width: '~39 km',
    note: 'Gulf oil and LNG exports',
  },
  {
    id: 'malacca',
    name: 'Strait of Malacca',
    kind: 'strait',
    coords: [100.35, 2.8],
    width: '~2.8 km (Phillips Channel)',
    note: 'Indian Ocean – South China Sea',
  },
  {
    id: 'singapore',
    name: 'Singapore Strait',
    kind: 'strait',
    coords: [103.85, 1.2],
    width: '~16 km',
    note: 'Malacca – South China Sea link',
  },
  {
    id: 'bab-el-mandeb',
    name: 'Bab-el-Mandeb',
    kind: 'strait',
    coords: [43.33, 12.6],
    width: '~29 km',
    note: 'Red Sea – Gulf of Aden',
  },
  {
    id: 'suez',
    name: 'Suez Canal',
    kind: 'canal',
    coords: [32.35, 30.6],
    width: '~205 m',
    note: 'Mediterranean – Red Sea',
  },
  {
    id: 'panama',
    name: 'Panama Canal',
    kind: 'canal',
    coords: [-79.68, 9.12],
    width: 'locks 55 m (Neopanamax)',
    note: 'Atlantic – Pacific',
  },
  {
    id: 'bosporus',
    name: 'Bosporus',
    kind: 'strait',
    coords: [29.05, 41.12],
    width: '~0.7 km',
    note: 'Black Sea – Sea of Marmara',
  },
  {
    id: 'dardanelles',
    name: 'Dardanelles',
    kind: 'strait',
    coords: [26.4, 40.2],
    width: '~1.2 km',
    note: 'Marmara – Aegean',
  },
  {
    id: 'gibraltar',
    name: 'Strait of Gibraltar',
    kind: 'strait',
    coords: [-5.6, 35.97],
    width: '~14 km',
    note: 'Atlantic – Mediterranean',
  },
  {
    id: 'dover',
    name: 'Strait of Dover',
    kind: 'strait',
    coords: [1.45, 51.0],
    width: '~33 km',
    note: 'Busiest traffic separation scheme',
  },
  {
    id: 'danish-straits',
    name: 'Danish Straits (Great Belt)',
    kind: 'strait',
    coords: [10.95, 55.3],
    width: '~16 km',
    note: 'Baltic access',
  },
  {
    id: 'taiwan',
    name: 'Taiwan Strait',
    kind: 'strait',
    coords: [119.6, 24.4],
    width: '~130 km',
    note: 'East – South China Sea',
  },
  {
    id: 'lombok',
    name: 'Lombok Strait',
    kind: 'strait',
    coords: [115.75, -8.7],
    width: '~20 km',
    note: 'Deep-draft Malacca alternative',
  },
  {
    id: 'sunda',
    name: 'Sunda Strait',
    kind: 'strait',
    coords: [105.8, -6.0],
    width: '~24 km',
    note: 'Java Sea – Indian Ocean',
  },
  {
    id: 'good-hope',
    name: 'Cape of Good Hope',
    kind: 'cape',
    coords: [18.47, -34.36],
    width: 'open ocean',
    note: 'Suez diversion route',
  },
  {
    id: 'magellan',
    name: 'Strait of Magellan',
    kind: 'strait',
    coords: [-70.9, -53.4],
    width: '~2 km (narrowest)',
    note: 'Atlantic – Pacific',
  },
  {
    id: 'kiel',
    name: 'Kiel Canal',
    kind: 'canal',
    coords: [9.6, 54.2],
    width: '~102 m',
    note: 'North Sea – Baltic',
  },
  {
    id: 'bering',
    name: 'Bering Strait',
    kind: 'strait',
    coords: [-168.95, 65.75],
    width: '~82 km',
    note: 'Arctic – Pacific',
  },
  {
    id: 'korea',
    name: 'Korea Strait',
    kind: 'strait',
    coords: [129.3, 34.6],
    width: '~200 km',
    note: 'Sea of Japan – East China Sea',
  },
  {
    id: 'mozambique',
    name: 'Mozambique Channel',
    kind: 'strait',
    coords: [40.5, -17.0],
    width: '~420 km',
    note: 'Cape route corridor',
  },
]);
